/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeployStatus from './DeployStatus';

/**
 * The DeployRequest model module.
 * @module model/DeployRequest
 * @version 1.0.0
 */
class DeployRequest {
    /**
     * Constructs a new <code>DeployRequest</code>.
     * @alias module:model/DeployRequest
     * @param deploymentStatus {module:model/DeployStatus} 
     */
    constructor(deploymentStatus) { 
        
        DeployRequest.initialize(this, deploymentStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deploymentStatus) { 
        obj['deploymentStatus'] = deploymentStatus;
    }

    /**
     * Constructs a <code>DeployRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeployRequest} obj Optional instance to populate.
     * @return {module:model/DeployRequest} The populated <code>DeployRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeployRequest();

            if (data.hasOwnProperty('deploymentStatus')) {
                obj['deploymentStatus'] = DeployStatus.constructFromObject(data['deploymentStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeployRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeployRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeployRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DeployRequest.RequiredProperties = ["deploymentStatus"];

/**
 * @member {module:model/DeployStatus} deploymentStatus
 */
DeployRequest.prototype['deploymentStatus'] = undefined;






export default DeployRequest;

