/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowLane from './DSWorkflowLane';
import DSWorkflowParallelExpression from './DSWorkflowParallelExpression';
import DSWorkflowStepTypesParallel from './DSWorkflowStepTypesParallel';

/**
 * The DSParallelStep model module.
 * @module model/DSParallelStep
 * @version 1.0.0
 */
class DSParallelStep {
    /**
     * Constructs a new <code>DSParallelStep</code>.
     * @alias module:model/DSParallelStep
     * @param name {String} 
     * @param id {String} 
     * @param type {module:model/DSWorkflowStepTypesParallel} 
     * @param lanes {Object.<String, module:model/DSWorkflowLane>} 
     * @param expression {module:model/DSWorkflowParallelExpression} 
     */
    constructor(name, id, type, lanes, expression) { 
        
        DSParallelStep.initialize(this, name, id, type, lanes, expression);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, id, type, lanes, expression) { 
        obj['name'] = name;
        obj['id'] = id;
        obj['type'] = type;
        obj['lanes'] = lanes;
        obj['expression'] = expression;
    }

    /**
     * Constructs a <code>DSParallelStep</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSParallelStep} obj Optional instance to populate.
     * @return {module:model/DSParallelStep} The populated <code>DSParallelStep</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSParallelStep();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowStepTypesParallel.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('lanes')) {
                obj['lanes'] = ApiClient.convertToType(data['lanes'], {'String': DSWorkflowLane});
            }
            if (data.hasOwnProperty('expression')) {
                obj['expression'] = DSWorkflowParallelExpression.constructFromObject(data['expression']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSParallelStep</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSParallelStep</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSParallelStep.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `expression`
        if (data['expression']) { // data not null
          DSWorkflowParallelExpression.validateJSON(data['expression']);
        }

        return true;
    }


}

DSParallelStep.RequiredProperties = ["name", "id", "type", "lanes", "expression"];

/**
 * @member {String} name
 */
DSParallelStep.prototype['name'] = undefined;

/**
 * @member {String} id
 */
DSParallelStep.prototype['id'] = undefined;

/**
 * @member {module:model/DSWorkflowStepTypesParallel} type
 */
DSParallelStep.prototype['type'] = undefined;

/**
 * @member {Object.<String, module:model/DSWorkflowLane>} lanes
 */
DSParallelStep.prototype['lanes'] = undefined;

/**
 * @member {module:model/DSWorkflowParallelExpression} expression
 */
DSParallelStep.prototype['expression'] = undefined;






export default DSParallelStep;

