/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowStepTypesDSTransformation from './DSWorkflowStepTypesDSTransformation';
import DSWorkflowTransformationExpression from './DSWorkflowTransformationExpression';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';

/**
 * The DSTransformationStep model module.
 * @module model/DSTransformationStep
 * @version 1.0.0
 */
class DSTransformationStep {
    /**
     * Constructs a new <code>DSTransformationStep</code>.
     * @alias module:model/DSTransformationStep
     * @param name {String} 
     * @param id {String} 
     * @param type {module:model/DSWorkflowStepTypesDSTransformation} 
     * @param config {Object} 
     * @param input {Object.<String, module:model/StringOrVariableOrTransformation>} A Record of strings to Strings, Variables, or Transformation Expressions
     * @param output {Object.<String, module:model/StringOrVariableOrTransformation>} A Record of strings to Strings, Variables, or Transformation Expressions
     * @param expression {module:model/DSWorkflowTransformationExpression} 
     */
    constructor(name, id, type, config, input, output, expression) { 
        
        DSTransformationStep.initialize(this, name, id, type, config, input, output, expression);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, id, type, config, input, output, expression) { 
        obj['name'] = name;
        obj['id'] = id;
        obj['type'] = type;
        obj['config'] = config;
        obj['input'] = input;
        obj['output'] = output;
        obj['expression'] = expression;
    }

    /**
     * Constructs a <code>DSTransformationStep</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSTransformationStep} obj Optional instance to populate.
     * @return {module:model/DSTransformationStep} The populated <code>DSTransformationStep</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSTransformationStep();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowStepTypesDSTransformation.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], Object);
            }
            if (data.hasOwnProperty('input')) {
                obj['input'] = ApiClient.convertToType(data['input'], {'String': StringOrVariableOrTransformation});
            }
            if (data.hasOwnProperty('output')) {
                obj['output'] = ApiClient.convertToType(data['output'], {'String': StringOrVariableOrTransformation});
            }
            if (data.hasOwnProperty('expression')) {
                obj['expression'] = DSWorkflowTransformationExpression.constructFromObject(data['expression']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSTransformationStep</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSTransformationStep</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSTransformationStep.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `expression`
        if (data['expression']) { // data not null
          DSWorkflowTransformationExpression.validateJSON(data['expression']);
        }

        return true;
    }


}

DSTransformationStep.RequiredProperties = ["name", "id", "type", "config", "input", "output", "expression"];

/**
 * @member {String} name
 */
DSTransformationStep.prototype['name'] = undefined;

/**
 * @member {String} id
 */
DSTransformationStep.prototype['id'] = undefined;

/**
 * @member {module:model/DSWorkflowStepTypesDSTransformation} type
 */
DSTransformationStep.prototype['type'] = undefined;

/**
 * @member {Object} config
 */
DSTransformationStep.prototype['config'] = undefined;

/**
 * A Record of strings to Strings, Variables, or Transformation Expressions
 * @member {Object.<String, module:model/StringOrVariableOrTransformation>} input
 */
DSTransformationStep.prototype['input'] = undefined;

/**
 * A Record of strings to Strings, Variables, or Transformation Expressions
 * @member {Object.<String, module:model/StringOrVariableOrTransformation>} output
 */
DSTransformationStep.prototype['output'] = undefined;

/**
 * @member {module:model/DSWorkflowTransformationExpression} expression
 */
DSTransformationStep.prototype['expression'] = undefined;






export default DSTransformationStep;

