/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowTransformationExpressionTypesConcatExpression from './DSWorkflowTransformationExpressionTypesConcatExpression';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';

/**
 * The DSWorkflowConcatExpression model module.
 * @module model/DSWorkflowConcatExpression
 * @version 1.0.0
 */
class DSWorkflowConcatExpression {
    /**
     * Constructs a new <code>DSWorkflowConcatExpression</code>.
     * @alias module:model/DSWorkflowConcatExpression
     * @param type {module:model/DSWorkflowTransformationExpressionTypesConcatExpression} 
     */
    constructor(type) { 
        
        DSWorkflowConcatExpression.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>DSWorkflowConcatExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSWorkflowConcatExpression} obj Optional instance to populate.
     * @return {module:model/DSWorkflowConcatExpression} The populated <code>DSWorkflowConcatExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSWorkflowConcatExpression();

            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowTransformationExpressionTypesConcatExpression.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('inputs')) {
                obj['inputs'] = ApiClient.convertToType(data['inputs'], [StringOrVariableOrTransformation]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSWorkflowConcatExpression</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSWorkflowConcatExpression</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSWorkflowConcatExpression.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['inputs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['inputs'])) {
                throw new Error("Expected the field `inputs` to be an array in the JSON data but got " + data['inputs']);
            }
            // validate the optional field `inputs` (array)
            for (const item of data['inputs']) {
                StringOrVariableOrTransformation.validateJSON(item);
            };
        }

        return true;
    }


}

DSWorkflowConcatExpression.RequiredProperties = ["type"];

/**
 * @member {module:model/DSWorkflowTransformationExpressionTypesConcatExpression} type
 */
DSWorkflowConcatExpression.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/StringOrVariableOrTransformation>} inputs
 */
DSWorkflowConcatExpression.prototype['inputs'] = undefined;






export default DSWorkflowConcatExpression;

