/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowBooleanExpression from './DSWorkflowBooleanExpression';
import DSWorkflowComparisonExpression from './DSWorkflowComparisonExpression';
import DSWorkflowComparisonExpressionLeftOperand from './DSWorkflowComparisonExpressionLeftOperand';
import DSWorkflowComparisonOperatorTypes from './DSWorkflowComparisonOperatorTypes';
import DSWorkflowExpressionTypesComparisonExpression from './DSWorkflowExpressionTypesComparisonExpression';
import DSWorkflowLogicalOperatorTypes from './DSWorkflowLogicalOperatorTypes';
// TODO: add anyof model support
