/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowVariableSourceTypesParticipant from './DSWorkflowVariableSourceTypesParticipant';
import ParticipantKeys from './ParticipantKeys';

/**
 * The DSWorkflowVariableFromParticipant model module.
 * @module model/DSWorkflowVariableFromParticipant
 * @version 1.0.0
 */
class DSWorkflowVariableFromParticipant {
    /**
     * Constructs a new <code>DSWorkflowVariableFromParticipant</code>.
     * DS Workflow Variable from a Participant
     * @alias module:model/DSWorkflowVariableFromParticipant
     * @param source {module:model/DSWorkflowVariableSourceTypesParticipant} 
     * @param key {module:model/ParticipantKeys} 
     * @param participantId {String} 
     */
    constructor(source, key, participantId) { 
        
        DSWorkflowVariableFromParticipant.initialize(this, source, key, participantId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, source, key, participantId) { 
        obj['source'] = source;
        obj['key'] = key;
        obj['participantId'] = participantId;
    }

    /**
     * Constructs a <code>DSWorkflowVariableFromParticipant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSWorkflowVariableFromParticipant} obj Optional instance to populate.
     * @return {module:model/DSWorkflowVariableFromParticipant} The populated <code>DSWorkflowVariableFromParticipant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSWorkflowVariableFromParticipant();

            if (data.hasOwnProperty('source')) {
                obj['source'] = DSWorkflowVariableSourceTypesParticipant.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ParticipantKeys.constructFromObject(data['key']);
            }
            if (data.hasOwnProperty('participantId')) {
                obj['participantId'] = ApiClient.convertToType(data['participantId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSWorkflowVariableFromParticipant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSWorkflowVariableFromParticipant</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSWorkflowVariableFromParticipant.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['participantId'] && !(typeof data['participantId'] === 'string' || data['participantId'] instanceof String)) {
            throw new Error("Expected the field `participantId` to be a primitive type in the JSON string but got " + data['participantId']);
        }

        return true;
    }


}

DSWorkflowVariableFromParticipant.RequiredProperties = ["source", "key", "participantId"];

/**
 * @member {module:model/DSWorkflowVariableSourceTypesParticipant} source
 */
DSWorkflowVariableFromParticipant.prototype['source'] = undefined;

/**
 * @member {module:model/ParticipantKeys} key
 */
DSWorkflowVariableFromParticipant.prototype['key'] = undefined;

/**
 * @member {String} participantId
 */
DSWorkflowVariableFromParticipant.prototype['participantId'] = undefined;






export default DSWorkflowVariableFromParticipant;

