/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowTransformationExpressionTypesLastIndexOfExpression from './DSWorkflowTransformationExpressionTypesLastIndexOfExpression';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';

/**
 * The DSWorkflowLastIndexOfExpression model module.
 * @module model/DSWorkflowLastIndexOfExpression
 * @version 1.0.0
 */
class DSWorkflowLastIndexOfExpression {
    /**
     * Constructs a new <code>DSWorkflowLastIndexOfExpression</code>.
     * @alias module:model/DSWorkflowLastIndexOfExpression
     * @param type {module:model/DSWorkflowTransformationExpressionTypesLastIndexOfExpression} 
     * @param text {module:model/StringOrVariableOrTransformation} 
     * @param searchText {module:model/StringOrVariableOrTransformation} 
     */
    constructor(type, text, searchText) { 
        
        DSWorkflowLastIndexOfExpression.initialize(this, type, text, searchText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, text, searchText) { 
        obj['type'] = type;
        obj['text'] = text;
        obj['searchText'] = searchText;
    }

    /**
     * Constructs a <code>DSWorkflowLastIndexOfExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSWorkflowLastIndexOfExpression} obj Optional instance to populate.
     * @return {module:model/DSWorkflowLastIndexOfExpression} The populated <code>DSWorkflowLastIndexOfExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSWorkflowLastIndexOfExpression();

            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowTransformationExpressionTypesLastIndexOfExpression.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = StringOrVariableOrTransformation.constructFromObject(data['text']);
            }
            if (data.hasOwnProperty('searchText')) {
                obj['searchText'] = StringOrVariableOrTransformation.constructFromObject(data['searchText']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSWorkflowLastIndexOfExpression</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSWorkflowLastIndexOfExpression</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSWorkflowLastIndexOfExpression.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `text`
        if (data['text']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['text']);
        }
        // validate the optional field `searchText`
        if (data['searchText']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['searchText']);
        }

        return true;
    }


}

DSWorkflowLastIndexOfExpression.RequiredProperties = ["type", "text", "searchText"];

/**
 * @member {module:model/DSWorkflowTransformationExpressionTypesLastIndexOfExpression} type
 */
DSWorkflowLastIndexOfExpression.prototype['type'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} text
 */
DSWorkflowLastIndexOfExpression.prototype['text'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} searchText
 */
DSWorkflowLastIndexOfExpression.prototype['searchText'] = undefined;






export default DSWorkflowLastIndexOfExpression;

