/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowTransformationExpressionTypesReplaceExpression from './DSWorkflowTransformationExpressionTypesReplaceExpression';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';

/**
 * The DSWorkflowReplaceExpression model module.
 * @module model/DSWorkflowReplaceExpression
 * @version 1.0.0
 */
class DSWorkflowReplaceExpression {
    /**
     * Constructs a new <code>DSWorkflowReplaceExpression</code>.
     * @alias module:model/DSWorkflowReplaceExpression
     * @param type {module:model/DSWorkflowTransformationExpressionTypesReplaceExpression} 
     * @param text {module:model/StringOrVariableOrTransformation} 
     * @param oldText {module:model/StringOrVariableOrTransformation} 
     * @param newText {module:model/StringOrVariableOrTransformation} 
     */
    constructor(type, text, oldText, newText) { 
        
        DSWorkflowReplaceExpression.initialize(this, type, text, oldText, newText);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, text, oldText, newText) { 
        obj['type'] = type;
        obj['text'] = text;
        obj['oldText'] = oldText;
        obj['newText'] = newText;
    }

    /**
     * Constructs a <code>DSWorkflowReplaceExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSWorkflowReplaceExpression} obj Optional instance to populate.
     * @return {module:model/DSWorkflowReplaceExpression} The populated <code>DSWorkflowReplaceExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSWorkflowReplaceExpression();

            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowTransformationExpressionTypesReplaceExpression.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = StringOrVariableOrTransformation.constructFromObject(data['text']);
            }
            if (data.hasOwnProperty('oldText')) {
                obj['oldText'] = StringOrVariableOrTransformation.constructFromObject(data['oldText']);
            }
            if (data.hasOwnProperty('newText')) {
                obj['newText'] = StringOrVariableOrTransformation.constructFromObject(data['newText']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSWorkflowReplaceExpression</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSWorkflowReplaceExpression</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSWorkflowReplaceExpression.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `text`
        if (data['text']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['text']);
        }
        // validate the optional field `oldText`
        if (data['oldText']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['oldText']);
        }
        // validate the optional field `newText`
        if (data['newText']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['newText']);
        }

        return true;
    }


}

DSWorkflowReplaceExpression.RequiredProperties = ["type", "text", "oldText", "newText"];

/**
 * @member {module:model/DSWorkflowTransformationExpressionTypesReplaceExpression} type
 */
DSWorkflowReplaceExpression.prototype['type'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} text
 */
DSWorkflowReplaceExpression.prototype['text'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} oldText
 */
DSWorkflowReplaceExpression.prototype['oldText'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} newText
 */
DSWorkflowReplaceExpression.prototype['newText'] = undefined;






export default DSWorkflowReplaceExpression;

