/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowExpressionTypesParallelExpression from './DSWorkflowExpressionTypesParallelExpression';

/**
 * The DSWorkflowParallelExpression model module.
 * @module model/DSWorkflowParallelExpression
 * @version 1.0.0
 */
class DSWorkflowParallelExpression {
    /**
     * Constructs a new <code>DSWorkflowParallelExpression</code>.
     * @alias module:model/DSWorkflowParallelExpression
     * @param type {module:model/DSWorkflowExpressionTypesParallelExpression} 
     * @param parallelCompletionSettings {Object.<String, Boolean>} 
     */
    constructor(type, parallelCompletionSettings) { 
        
        DSWorkflowParallelExpression.initialize(this, type, parallelCompletionSettings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, parallelCompletionSettings) { 
        obj['type'] = type;
        obj['parallelCompletionSettings'] = parallelCompletionSettings;
    }

    /**
     * Constructs a <code>DSWorkflowParallelExpression</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DSWorkflowParallelExpression} obj Optional instance to populate.
     * @return {module:model/DSWorkflowParallelExpression} The populated <code>DSWorkflowParallelExpression</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DSWorkflowParallelExpression();

            if (data.hasOwnProperty('type')) {
                obj['type'] = DSWorkflowExpressionTypesParallelExpression.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('parallelCompletionSettings')) {
                obj['parallelCompletionSettings'] = ApiClient.convertToType(data['parallelCompletionSettings'], {'String': 'Boolean'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DSWorkflowParallelExpression</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DSWorkflowParallelExpression</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DSWorkflowParallelExpression.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DSWorkflowParallelExpression.RequiredProperties = ["type", "parallelCompletionSettings"];

/**
 * @member {module:model/DSWorkflowExpressionTypesParallelExpression} type
 */
DSWorkflowParallelExpression.prototype['type'] = undefined;

/**
 * @member {Object.<String, Boolean>} parallelCompletionSettings
 */
DSWorkflowParallelExpression.prototype['parallelCompletionSettings'] = undefined;






export default DSWorkflowParallelExpression;

