/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ErrorCodes.
* @enum {}
* @readonly
*/
export default class ErrorCodes {
    
        /**
         * value: "ERR_10001"
         * @const
         */
        "10001" = "ERR_10001";

    
        /**
         * value: "ERR_10002"
         * @const
         */
        "10002" = "ERR_10002";

    
        /**
         * value: "ERR_10003"
         * @const
         */
        "10003" = "ERR_10003";

    
        /**
         * value: "ERR_10004"
         * @const
         */
        "10004" = "ERR_10004";

    
        /**
         * value: "ERR_10005"
         * @const
         */
        "10005" = "ERR_10005";

    
        /**
         * value: "ERR_10006"
         * @const
         */
        "10006" = "ERR_10006";

    
        /**
         * value: "ERR_10007"
         * @const
         */
        "10007" = "ERR_10007";

    
        /**
         * value: "ERR_10008"
         * @const
         */
        "10008" = "ERR_10008";

    
        /**
         * value: "ERR_10009"
         * @const
         */
        "10009" = "ERR_10009";

    
        /**
         * value: "ERR_10101"
         * @const
         */
        "10101" = "ERR_10101";

    
        /**
         * value: "ERR_10201"
         * @const
         */
        "10201" = "ERR_10201";

    
        /**
         * value: "ERR_10202"
         * @const
         */
        "10202" = "ERR_10202";

    
        /**
         * value: "ERR_10301"
         * @const
         */
        "10301" = "ERR_10301";

    
        /**
         * value: "ERR_10302"
         * @const
         */
        "10302" = "ERR_10302";

    
        /**
         * value: "ERR_10801"
         * @const
         */
        "10801" = "ERR_10801";

    
        /**
         * value: "ERR_10802"
         * @const
         */
        "10802" = "ERR_10802";

    
        /**
         * value: "ERR_10999"
         * @const
         */
        "10999" = "ERR_10999";

    

    /**
    * Returns a <code>ErrorCodes</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ErrorCodes} The enum <code>ErrorCodes</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

