/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowDocGenDocOutputFormat from './DSWorkflowDocGenDocOutputFormat';
import DSWorkflowVariable from './DSWorkflowVariable';
import ESignDocumentFromESignTemplate from './ESignDocumentFromESignTemplate';
import ESignDocumentFromPreviousStep from './ESignDocumentFromPreviousStep';
import ESignDocumentTypesFromDSTemplate from './ESignDocumentTypesFromDSTemplate';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';
// TODO: add anyof model support
