/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DSWorkflowDocGenDocOutputFormat from './DSWorkflowDocGenDocOutputFormat';
import ESignDocumentTypesFromDSTemplate from './ESignDocumentTypesFromDSTemplate';
import StringOrVariableOrTransformation from './StringOrVariableOrTransformation';

/**
 * The ESignDocumentFromESignTemplate model module.
 * @module model/ESignDocumentFromESignTemplate
 * @version 1.0.0
 */
class ESignDocumentFromESignTemplate {
    /**
     * Constructs a new <code>ESignDocumentFromESignTemplate</code>.
     * @alias module:model/ESignDocumentFromESignTemplate
     * @param type {module:model/ESignDocumentTypesFromDSTemplate} 
     * @param eSignTemplateId {String} 
     * @param fileExtension {module:model/DSWorkflowDocGenDocOutputFormat} 
     * @param name {module:model/StringOrVariableOrTransformation} 
     */
    constructor(type, eSignTemplateId, fileExtension, name) { 
        
        ESignDocumentFromESignTemplate.initialize(this, type, eSignTemplateId, fileExtension, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, eSignTemplateId, fileExtension, name) { 
        obj['type'] = type;
        obj['eSignTemplateId'] = eSignTemplateId;
        obj['fileExtension'] = fileExtension;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ESignDocumentFromESignTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ESignDocumentFromESignTemplate} obj Optional instance to populate.
     * @return {module:model/ESignDocumentFromESignTemplate} The populated <code>ESignDocumentFromESignTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ESignDocumentFromESignTemplate();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ESignDocumentTypesFromDSTemplate.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('eSignTemplateId')) {
                obj['eSignTemplateId'] = ApiClient.convertToType(data['eSignTemplateId'], 'String');
            }
            if (data.hasOwnProperty('fileExtension')) {
                obj['fileExtension'] = DSWorkflowDocGenDocOutputFormat.constructFromObject(data['fileExtension']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = StringOrVariableOrTransformation.constructFromObject(data['name']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ESignDocumentFromESignTemplate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ESignDocumentFromESignTemplate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ESignDocumentFromESignTemplate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['eSignTemplateId'] && !(typeof data['eSignTemplateId'] === 'string' || data['eSignTemplateId'] instanceof String)) {
            throw new Error("Expected the field `eSignTemplateId` to be a primitive type in the JSON string but got " + data['eSignTemplateId']);
        }
        // validate the optional field `name`
        if (data['name']) { // data not null
          StringOrVariableOrTransformation.validateJSON(data['name']);
        }

        return true;
    }


}

ESignDocumentFromESignTemplate.RequiredProperties = ["type", "eSignTemplateId", "fileExtension", "name"];

/**
 * @member {module:model/ESignDocumentTypesFromDSTemplate} type
 */
ESignDocumentFromESignTemplate.prototype['type'] = undefined;

/**
 * @member {String} eSignTemplateId
 */
ESignDocumentFromESignTemplate.prototype['eSignTemplateId'] = undefined;

/**
 * @member {module:model/DSWorkflowDocGenDocOutputFormat} fileExtension
 */
ESignDocumentFromESignTemplate.prototype['fileExtension'] = undefined;

/**
 * @member {module:model/StringOrVariableOrTransformation} name
 */
ESignDocumentFromESignTemplate.prototype['name'] = undefined;






export default ESignDocumentFromESignTemplate;

