/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationErrors from './ValidationErrors';
import WorkflowDefinition from './WorkflowDefinition';

/**
 * The NewOrUpdatedWorkflowDefinitionResponse model module.
 * @module model/NewOrUpdatedWorkflowDefinitionResponse
 * @version 1.0.0
 */
class NewOrUpdatedWorkflowDefinitionResponse {
    /**
     * Constructs a new <code>NewOrUpdatedWorkflowDefinitionResponse</code>.
     * @alias module:model/NewOrUpdatedWorkflowDefinitionResponse
     * @param workflowDefinitionId {String} 
     * @param workflowDefinition {module:model/WorkflowDefinition} 
     * @param isValidWorkflowDefinition {Boolean} 
     * @param validationErrors {Array.<module:model/ValidationErrors>} 
     */
    constructor(workflowDefinitionId, workflowDefinition, isValidWorkflowDefinition, validationErrors) { 
        
        NewOrUpdatedWorkflowDefinitionResponse.initialize(this, workflowDefinitionId, workflowDefinition, isValidWorkflowDefinition, validationErrors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workflowDefinitionId, workflowDefinition, isValidWorkflowDefinition, validationErrors) { 
        obj['workflowDefinitionId'] = workflowDefinitionId;
        obj['workflowDefinition'] = workflowDefinition;
        obj['isValidWorkflowDefinition'] = isValidWorkflowDefinition;
        obj['validationErrors'] = validationErrors;
    }

    /**
     * Constructs a <code>NewOrUpdatedWorkflowDefinitionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewOrUpdatedWorkflowDefinitionResponse} obj Optional instance to populate.
     * @return {module:model/NewOrUpdatedWorkflowDefinitionResponse} The populated <code>NewOrUpdatedWorkflowDefinitionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewOrUpdatedWorkflowDefinitionResponse();

            if (data.hasOwnProperty('workflowDefinitionId')) {
                obj['workflowDefinitionId'] = ApiClient.convertToType(data['workflowDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('workflowDefinition')) {
                obj['workflowDefinition'] = WorkflowDefinition.constructFromObject(data['workflowDefinition']);
            }
            if (data.hasOwnProperty('isValidWorkflowDefinition')) {
                obj['isValidWorkflowDefinition'] = ApiClient.convertToType(data['isValidWorkflowDefinition'], 'Boolean');
            }
            if (data.hasOwnProperty('validationErrors')) {
                obj['validationErrors'] = ApiClient.convertToType(data['validationErrors'], [ValidationErrors]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewOrUpdatedWorkflowDefinitionResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewOrUpdatedWorkflowDefinitionResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NewOrUpdatedWorkflowDefinitionResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['workflowDefinitionId'] && !(typeof data['workflowDefinitionId'] === 'string' || data['workflowDefinitionId'] instanceof String)) {
            throw new Error("Expected the field `workflowDefinitionId` to be a primitive type in the JSON string but got " + data['workflowDefinitionId']);
        }
        // validate the optional field `workflowDefinition`
        if (data['workflowDefinition']) { // data not null
          WorkflowDefinition.validateJSON(data['workflowDefinition']);
        }
        if (data['validationErrors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['validationErrors'])) {
                throw new Error("Expected the field `validationErrors` to be an array in the JSON data but got " + data['validationErrors']);
            }
            // validate the optional field `validationErrors` (array)
            for (const item of data['validationErrors']) {
                ValidationErrors.validateJSON(item);
            };
        }

        return true;
    }


}

NewOrUpdatedWorkflowDefinitionResponse.RequiredProperties = ["workflowDefinitionId", "workflowDefinition", "isValidWorkflowDefinition", "validationErrors"];

/**
 * @member {String} workflowDefinitionId
 */
NewOrUpdatedWorkflowDefinitionResponse.prototype['workflowDefinitionId'] = undefined;

/**
 * @member {module:model/WorkflowDefinition} workflowDefinition
 */
NewOrUpdatedWorkflowDefinitionResponse.prototype['workflowDefinition'] = undefined;

/**
 * @member {Boolean} isValidWorkflowDefinition
 */
NewOrUpdatedWorkflowDefinitionResponse.prototype['isValidWorkflowDefinition'] = undefined;

/**
 * @member {Array.<module:model/ValidationErrors>} validationErrors
 */
NewOrUpdatedWorkflowDefinitionResponse.prototype['validationErrors'] = undefined;






export default NewOrUpdatedWorkflowDefinitionResponse;

