/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ParticipantKeys.
* @enum {}
* @readonly
*/
export default class ParticipantKeys {
    
        /**
         * value: "participantEmail"
         * @const
         */
        "participantEmail" = "participantEmail";

    
        /**
         * value: "participantFirstName"
         * @const
         */
        "participantFirstName" = "participantFirstName";

    
        /**
         * value: "participantLastName"
         * @const
         */
        "participantLastName" = "participantLastName";

    

    /**
    * Returns a <code>ParticipantKeys</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ParticipantKeys} The enum <code>ParticipantKeys</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

