/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProgressInstance model module.
 * @module model/ProgressInstance
 * @version 1.0.0
 */
class ProgressInstance {
    /**
     * Constructs a new <code>ProgressInstance</code>.
     * The progress information for a workflow instance
     * @alias module:model/ProgressInstance
     */
    constructor() { 
        
        ProgressInstance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProgressInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProgressInstance} obj Optional instance to populate.
     * @return {module:model/ProgressInstance} The populated <code>ProgressInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProgressInstance();

            if (data.hasOwnProperty('totalSteps')) {
                obj['totalSteps'] = ApiClient.convertToType(data['totalSteps'], 'Number');
            }
            if (data.hasOwnProperty('completedSteps')) {
                obj['completedSteps'] = ApiClient.convertToType(data['completedSteps'], 'Number');
            }
            if (data.hasOwnProperty('currentCompletedStepName')) {
                obj['currentCompletedStepName'] = ApiClient.convertToType(data['currentCompletedStepName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProgressInstance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProgressInstance</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['currentCompletedStepName'] && !(typeof data['currentCompletedStepName'] === 'string' || data['currentCompletedStepName'] instanceof String)) {
            throw new Error("Expected the field `currentCompletedStepName` to be a primitive type in the JSON string but got " + data['currentCompletedStepName']);
        }

        return true;
    }


}



/**
 * The total number of steps for this workflow instance
 * @member {Number} totalSteps
 */
ProgressInstance.prototype['totalSteps'] = undefined;

/**
 * The number of completed steps for this workflow instance
 * @member {Number} completedSteps
 */
ProgressInstance.prototype['completedSteps'] = undefined;

/**
 * The last completed step name
 * @member {String} currentCompletedStepName
 */
ProgressInstance.prototype['currentCompletedStepName'] = undefined;






export default ProgressInstance;

