/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowDefinitionMetadata from './WorkflowDefinitionMetadata';

/**
 * The WorkflowDefinitionList model module.
 * @module model/WorkflowDefinitionList
 * @version 1.0.0
 */
class WorkflowDefinitionList {
    /**
     * Constructs a new <code>WorkflowDefinitionList</code>.
     * Returns a list of workflow definitions&#39; metadata (0 or more).
     * @alias module:model/WorkflowDefinitionList
     */
    constructor() { 
        
        WorkflowDefinitionList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowDefinitionList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowDefinitionList} obj Optional instance to populate.
     * @return {module:model/WorkflowDefinitionList} The populated <code>WorkflowDefinitionList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowDefinitionList();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [WorkflowDefinitionMetadata]);
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowDefinitionList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowDefinitionList</code>.
     */
    static validateJSON(data) {
        if (data['value']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['value'])) {
                throw new Error("Expected the field `value` to be an array in the JSON data but got " + data['value']);
            }
            // validate the optional field `value` (array)
            for (const item of data['value']) {
                WorkflowDefinitionMetadata.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Array of workflow definition metadata
 * @member {Array.<module:model/WorkflowDefinitionMetadata>} value
 */
WorkflowDefinitionList.prototype['value'] = undefined;

/**
 * Total number of definitions returned
 * @member {Number} count
 */
WorkflowDefinitionList.prototype['count'] = undefined;






export default WorkflowDefinitionList;

