/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowStepHistory from './WorkflowStepHistory';

/**
 * The WorkflowStepHistoryList model module.
 * @module model/WorkflowStepHistoryList
 * @version 1.0.0
 */
class WorkflowStepHistoryList {
    /**
     * Constructs a new <code>WorkflowStepHistoryList</code>.
     * Returns the history of the workflow instance steps.
     * @alias module:model/WorkflowStepHistoryList
     */
    constructor() { 
        
        WorkflowStepHistoryList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowStepHistoryList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowStepHistoryList} obj Optional instance to populate.
     * @return {module:model/WorkflowStepHistoryList} The populated <code>WorkflowStepHistoryList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowStepHistoryList();

            if (data.hasOwnProperty('stepHistory')) {
                obj['stepHistory'] = ApiClient.convertToType(data['stepHistory'], [WorkflowStepHistory]);
            }
            if (data.hasOwnProperty('resultSize')) {
                obj['resultSize'] = ApiClient.convertToType(data['resultSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowStepHistoryList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowStepHistoryList</code>.
     */
    static validateJSON(data) {
        if (data['stepHistory']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stepHistory'])) {
                throw new Error("Expected the field `stepHistory` to be an array in the JSON data but got " + data['stepHistory']);
            }
            // validate the optional field `stepHistory` (array)
            for (const item of data['stepHistory']) {
                WorkflowStepHistory.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Array of Workflow Step History
 * @member {Array.<module:model/WorkflowStepHistory>} stepHistory
 */
WorkflowStepHistoryList.prototype['stepHistory'] = undefined;

/**
 * Total number of workflow step history returned
 * @member {Number} resultSize
 */
WorkflowStepHistoryList.prototype['resultSize'] = undefined;






export default WorkflowStepHistoryList;

