/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowMetadataStatus from './WorkflowMetadataStatus';

/**
 * The WorkflowDefinitionMetadata model module.
 * @module model/WorkflowDefinitionMetadata
 * @version 1.0.0
 */
class WorkflowDefinitionMetadata {
    /**
     * Constructs a new <code>WorkflowDefinitionMetadata</code>.
     * A DS workflow definition&#39;s metadata.
     * @alias module:model/WorkflowDefinitionMetadata
     * @param id {String} 
     */
    constructor(id) { 
        
        WorkflowDefinitionMetadata.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>WorkflowDefinitionMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowDefinitionMetadata} obj Optional instance to populate.
     * @return {module:model/WorkflowDefinitionMetadata} The populated <code>WorkflowDefinitionMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowDefinitionMetadata();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('lastUpdatedDate')) {
                obj['lastUpdatedDate'] = ApiClient.convertToType(data['lastUpdatedDate'], 'Date');
            }
            if (data.hasOwnProperty('triggerUrl')) {
                obj['triggerUrl'] = ApiClient.convertToType(data['triggerUrl'], 'String');
            }
            if (data.hasOwnProperty('isDraft')) {
                obj['isDraft'] = ApiClient.convertToType(data['isDraft'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = WorkflowMetadataStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('lastDeployedId')) {
                obj['lastDeployedId'] = ApiClient.convertToType(data['lastDeployedId'], 'String');
            }
            if (data.hasOwnProperty('lastDeployedVersion')) {
                obj['lastDeployedVersion'] = ApiClient.convertToType(data['lastDeployedVersion'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowDefinitionMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowDefinitionMetadata</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowDefinitionMetadata.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['accountId'] && !(typeof data['accountId'] === 'string' || data['accountId'] instanceof String)) {
            throw new Error("Expected the field `accountId` to be a primitive type in the JSON string but got " + data['accountId']);
        }
        // ensure the json data is a string
        if (data['triggerUrl'] && !(typeof data['triggerUrl'] === 'string' || data['triggerUrl'] instanceof String)) {
            throw new Error("Expected the field `triggerUrl` to be a primitive type in the JSON string but got " + data['triggerUrl']);
        }
        // ensure the json data is a string
        if (data['lastDeployedId'] && !(typeof data['lastDeployedId'] === 'string' || data['lastDeployedId'] instanceof String)) {
            throw new Error("Expected the field `lastDeployedId` to be a primitive type in the JSON string but got " + data['lastDeployedId']);
        }
        // ensure the json data is a string
        if (data['lastDeployedVersion'] && !(typeof data['lastDeployedVersion'] === 'string' || data['lastDeployedVersion'] instanceof String)) {
            throw new Error("Expected the field `lastDeployedVersion` to be a primitive type in the JSON string but got " + data['lastDeployedVersion']);
        }

        return true;
    }


}

WorkflowDefinitionMetadata.RequiredProperties = ["id"];

/**
 * @member {String} id
 */
WorkflowDefinitionMetadata.prototype['id'] = undefined;

/**
 * @member {String} name
 */
WorkflowDefinitionMetadata.prototype['name'] = undefined;

/**
 * @member {String} accountId
 */
WorkflowDefinitionMetadata.prototype['accountId'] = undefined;

/**
 * The date the workflow was created
 * @member {Date} createdDate
 */
WorkflowDefinitionMetadata.prototype['createdDate'] = undefined;

/**
 * The date the workflow was last updated
 * @member {Date} lastUpdatedDate
 */
WorkflowDefinitionMetadata.prototype['lastUpdatedDate'] = undefined;

/**
 * @member {String} triggerUrl
 */
WorkflowDefinitionMetadata.prototype['triggerUrl'] = undefined;

/**
 * @member {Boolean} isDraft
 */
WorkflowDefinitionMetadata.prototype['isDraft'] = undefined;

/**
 * @member {module:model/WorkflowMetadataStatus} status
 */
WorkflowDefinitionMetadata.prototype['status'] = undefined;

/**
 * @member {String} lastDeployedId
 */
WorkflowDefinitionMetadata.prototype['lastDeployedId'] = undefined;

/**
 * @member {String} lastDeployedVersion
 */
WorkflowDefinitionMetadata.prototype['lastDeployedVersion'] = undefined;






export default WorkflowDefinitionMetadata;

