/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WorkflowDeleteResponse model module.
 * @module model/WorkflowDeleteResponse
 * @version 1.0.0
 */
class WorkflowDeleteResponse {
    /**
     * Constructs a new <code>WorkflowDeleteResponse</code>.
     * @alias module:model/WorkflowDeleteResponse
     * @param workflowDefinitionId {String} 
     * @param pollUrl {String} 
     */
    constructor(workflowDefinitionId, pollUrl) { 
        
        WorkflowDeleteResponse.initialize(this, workflowDefinitionId, pollUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workflowDefinitionId, pollUrl) { 
        obj['workflowDefinitionId'] = workflowDefinitionId;
        obj['pollUrl'] = pollUrl;
    }

    /**
     * Constructs a <code>WorkflowDeleteResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowDeleteResponse} obj Optional instance to populate.
     * @return {module:model/WorkflowDeleteResponse} The populated <code>WorkflowDeleteResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowDeleteResponse();

            if (data.hasOwnProperty('workflowDefinitionId')) {
                obj['workflowDefinitionId'] = ApiClient.convertToType(data['workflowDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('pollUrl')) {
                obj['pollUrl'] = ApiClient.convertToType(data['pollUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowDeleteResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowDeleteResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WorkflowDeleteResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['workflowDefinitionId'] && !(typeof data['workflowDefinitionId'] === 'string' || data['workflowDefinitionId'] instanceof String)) {
            throw new Error("Expected the field `workflowDefinitionId` to be a primitive type in the JSON string but got " + data['workflowDefinitionId']);
        }
        // ensure the json data is a string
        if (data['pollUrl'] && !(typeof data['pollUrl'] === 'string' || data['pollUrl'] instanceof String)) {
            throw new Error("Expected the field `pollUrl` to be a primitive type in the JSON string but got " + data['pollUrl']);
        }

        return true;
    }


}

WorkflowDeleteResponse.RequiredProperties = ["workflowDefinitionId", "pollUrl"];

/**
 * @member {String} workflowDefinitionId
 */
WorkflowDeleteResponse.prototype['workflowDefinitionId'] = undefined;

/**
 * @member {String} pollUrl
 */
WorkflowDeleteResponse.prototype['pollUrl'] = undefined;






export default WorkflowDeleteResponse;

