/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkflowInstance from './WorkflowInstance';

/**
 * The WorkflowInstancesList model module.
 * @module model/WorkflowInstancesList
 * @version 1.0.0
 */
class WorkflowInstancesList {
    /**
     * Constructs a new <code>WorkflowInstancesList</code>.
     * Returns a list of workflow instances (0 or more).
     * @alias module:model/WorkflowInstancesList
     */
    constructor() { 
        
        WorkflowInstancesList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkflowInstancesList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkflowInstancesList} obj Optional instance to populate.
     * @return {module:model/WorkflowInstancesList} The populated <code>WorkflowInstancesList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkflowInstancesList();

            if (data.hasOwnProperty('instances')) {
                obj['instances'] = ApiClient.convertToType(data['instances'], [WorkflowInstance]);
            }
            if (data.hasOwnProperty('resultSize')) {
                obj['resultSize'] = ApiClient.convertToType(data['resultSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WorkflowInstancesList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WorkflowInstancesList</code>.
     */
    static validateJSON(data) {
        if (data['instances']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['instances'])) {
                throw new Error("Expected the field `instances` to be an array in the JSON data but got " + data['instances']);
            }
            // validate the optional field `instances` (array)
            for (const item of data['instances']) {
                WorkflowInstance.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Array of Workflow Instances
 * @member {Array.<module:model/WorkflowInstance>} instances
 */
WorkflowInstancesList.prototype['instances'] = undefined;

/**
 * Total number of instances returned
 * @member {Number} resultSize
 */
WorkflowInstancesList.prototype['resultSize'] = undefined;






export default WorkflowInstancesList;

