/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WriteConfigurationInstancesRequestConfigInstancesInner from './WriteConfigurationInstancesRequestConfigInstancesInner';

/**
 * The WriteConfigurationInstancesRequest model module.
 * @module model/WriteConfigurationInstancesRequest
 * @version 1.0.0
 */
class WriteConfigurationInstancesRequest {
    /**
     * Constructs a new <code>WriteConfigurationInstancesRequest</code>.
     * @alias module:model/WriteConfigurationInstancesRequest
     * @param configInstances {Array.<module:model/WriteConfigurationInstancesRequestConfigInstancesInner>} 
     */
    constructor(configInstances) { 
        
        WriteConfigurationInstancesRequest.initialize(this, configInstances);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, configInstances) { 
        obj['configInstances'] = configInstances;
    }

    /**
     * Constructs a <code>WriteConfigurationInstancesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WriteConfigurationInstancesRequest} obj Optional instance to populate.
     * @return {module:model/WriteConfigurationInstancesRequest} The populated <code>WriteConfigurationInstancesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WriteConfigurationInstancesRequest();

            if (data.hasOwnProperty('configInstances')) {
                obj['configInstances'] = ApiClient.convertToType(data['configInstances'], [WriteConfigurationInstancesRequestConfigInstancesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WriteConfigurationInstancesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WriteConfigurationInstancesRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WriteConfigurationInstancesRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['configInstances']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['configInstances'])) {
                throw new Error("Expected the field `configInstances` to be an array in the JSON data but got " + data['configInstances']);
            }
            // validate the optional field `configInstances` (array)
            for (const item of data['configInstances']) {
                WriteConfigurationInstancesRequestConfigInstancesInner.validateJSON(item);
            };
        }

        return true;
    }


}

WriteConfigurationInstancesRequest.RequiredProperties = ["configInstances"];

/**
 * @member {Array.<module:model/WriteConfigurationInstancesRequestConfigInstancesInner>} configInstances
 */
WriteConfigurationInstancesRequest.prototype['configInstances'] = undefined;






export default WriteConfigurationInstancesRequest;

