/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WriteConfigurationInstancesRequestConfigInstancesInner model module.
 * @module model/WriteConfigurationInstancesRequestConfigInstancesInner
 * @version 1.0.0
 */
class WriteConfigurationInstancesRequestConfigInstancesInner {
    /**
     * Constructs a new <code>WriteConfigurationInstancesRequestConfigInstancesInner</code>.
     * @alias module:model/WriteConfigurationInstancesRequestConfigInstancesInner
     */
    constructor() { 
        
        WriteConfigurationInstancesRequestConfigInstancesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WriteConfigurationInstancesRequestConfigInstancesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WriteConfigurationInstancesRequestConfigInstancesInner} obj Optional instance to populate.
     * @return {module:model/WriteConfigurationInstancesRequestConfigInstancesInner} The populated <code>WriteConfigurationInstancesRequestConfigInstancesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WriteConfigurationInstancesRequestConfigInstancesInner();

            if (data.hasOwnProperty('stepId')) {
                obj['stepId'] = ApiClient.convertToType(data['stepId'], 'String');
            }
            if (data.hasOwnProperty('savedValues')) {
                obj['savedValues'] = ApiClient.convertToType(data['savedValues'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WriteConfigurationInstancesRequestConfigInstancesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WriteConfigurationInstancesRequestConfigInstancesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['stepId'] && !(typeof data['stepId'] === 'string' || data['stepId'] instanceof String)) {
            throw new Error("Expected the field `stepId` to be a primitive type in the JSON string but got " + data['stepId']);
        }

        return true;
    }


}



/**
 * @member {String} stepId
 */
WriteConfigurationInstancesRequestConfigInstancesInner.prototype['stepId'] = undefined;

/**
 * @member {Object.<String, Object>} savedValues
 */
WriteConfigurationInstancesRequestConfigInstancesInner.prototype['savedValues'] = undefined;






export default WriteConfigurationInstancesRequestConfigInstancesInner;

