/**
 * Workflows APIs
 * Workflows authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aow@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WriteConfigurationInstanceRequest model module.
 * @module model/WriteConfigurationInstanceRequest
 * @version 1.0.0
 */
class WriteConfigurationInstanceRequest {
    /**
     * Constructs a new <code>WriteConfigurationInstanceRequest</code>.
     * @alias module:model/WriteConfigurationInstanceRequest
     * @param savedValues {Object.<String, Object>} 
     */
    constructor(savedValues) { 
        
        WriteConfigurationInstanceRequest.initialize(this, savedValues);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, savedValues) { 
        obj['savedValues'] = savedValues;
    }

    /**
     * Constructs a <code>WriteConfigurationInstanceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WriteConfigurationInstanceRequest} obj Optional instance to populate.
     * @return {module:model/WriteConfigurationInstanceRequest} The populated <code>WriteConfigurationInstanceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WriteConfigurationInstanceRequest();

            if (data.hasOwnProperty('savedValues')) {
                obj['savedValues'] = ApiClient.convertToType(data['savedValues'], {'String': Object});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WriteConfigurationInstanceRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WriteConfigurationInstanceRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WriteConfigurationInstanceRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

WriteConfigurationInstanceRequest.RequiredProperties = ["savedValues"];

/**
 * @member {Object.<String, Object>} savedValues
 */
WriteConfigurationInstanceRequest.prototype['savedValues'] = undefined;






export default WriteConfigurationInstanceRequest;

